### ISSUE TITLE
oAuth token is sent to alfresco.com

### ISSUE THREAD

**Issue by angelborroy-ks** [Alfresco/google-docs#7]
Google callback URL is a hardcoded value ("http://www.alfresco.com/google-auth-return.html”) at https://github.com/Alfresco/google-docs/blob/master/Google%20Docs%20Repository/src/main/java/org/alfresco/integrations/google/docs/GoogleDocsConstants.java

It’s used to establish a callback URL in line 744 of
https://github.com/Alfresco/google-docs/blob/master/Google%20Docs%20Repository/src/main/java/org/alfresco/integrations/google/docs/service/GoogleDocsServiceImpl.java 

So oAuth token is sent effectively to “alfresco.com”
view-source:https://www.alfresco.com/google-auth-return.html

Is there any possibility to make this callback url customizable?

**Comment by jottley** [comment]
We could look at adding that. It would only be valid if you provide your own oauth config.

**Comment by mobreza** [comment]
Agreed; individual (on-site) Alfresco systems require their own Google API keys.

**Comment by jottley** [comment]
If you are building from here that is true.  If you are using the community provided amps (https://wiki.alfresco.com/wiki/Community_file_list_5.0.d#GoogleDocs_integration) you don't. 

If you *must* have your own keys you can still use the public endpoint (https://www.alfresco.com/google-auth-return.html). The endpoint is a universal proxy that allows the oauth dance to occur without the need for much configuration redirecting the oauth flow back to the local instance.

If this is not acceptable then we can work on making it more configurable.

**Comment by montgolfiere** [comment]
Dear @angelborroy-ks 

Many thanks for your feedback. Hopefully @jottley previous comment was acceptable.

Just an FYI, we have now deprecated this old git repo in favour of a new git repo (please see https://github.com/Alfresco/google-docs/blob/master/README.md).

If you're still interested in contributing then we would appreciate if you could switch over to the new git repo (https://github.com/Alfresco/googledrive/tree/dev_3.1.0) along with raising an ALF JIRA with contribution agreement https://github.com/Alfresco/googledrive#contributing

Thanks again for your continued support.

Regards,
@montgolfiere
