### ISSUE TITLE
New branch needed

### ISSUE THREAD

**Issue by kkorchemkin** [Alfresco/google-docs#9]
Hello.

As you may know, the 2.0.5 version does not work with Alfresco 4.2.f because of using an outdated Google Docs API.

So I made some code changes to make the google-docs plugin work with Alfresco 4.2.f.

I would want to create the pull request and push it into a new branch (eg. alfresco4.2).

Could you please cerate the branch so I would push the changes.

Thank you.

Regards.

**Comment by jottley** [comment]
2.0.5 is no longer a supported version of the integration.  Please upgrade to the lated 3.0.x release.
